Repository TEAM-Arabyte/Arabyte_AOS, pull requests merged in 2025-04, with the labels that each got.

#16 Feat/#15 Common Component etc (List, Bar, Chip)
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/ArabyteReviewItem.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/ArabyteTopAppBar.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/chip/ArabyteLocationChip.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/mypage/component/MyPageMyContractItem.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/component/NoticeBoardCategoryChip.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/component/NoticeBoardWriterChip.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/onboarding/component/OnboardingNumberChip.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/review/component/ReviewCategoryChip.kt
  app/src/main/res/drawable/ic_all_back_button_45.xml
  app/src/main/res/drawable/ic_all_check_20.xml
  app/src/main/res/drawable/ic_all_check_dots_20.xml
  app/src/main/res/drawable/ic_all_optional_button_45.xml
  app/src/main/res/values/strings.xml
Labels: feature, hwiwon

#17 Feat: SplashScreen UI 구현
  app/build.gradle.kts
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/login/LoginScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/MainViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/splash/SplashScreen.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: feature, minseok

#21 Feat: SignUp UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasource/LocationsRemoteDataSource.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasourceimpl/LocationsRemoteDataSourceImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/response/LocationDataDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/service/LocationsService.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/mapper/todomain/DataMapper.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/mapper/todomain/LocationMapper.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/repositoryimpl/DummyRepositoryImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/repositoryimpl/LocationsRepositoryImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/util/ApiConstraints.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/DataSourceModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/RepositoryModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/ServiceModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/LocationData.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/repository/LocationsRepository.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/dummy/DummyUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/locations/GetDongUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/locations/GetGuUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/locations/GetSidoUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/type/component/ArabyteBoardCategoryType.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/type/component/ArabyteCareerTextFieldType.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/type/component/ArabyteCategoryType.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/type/component/ArabyteFilteringType.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/type/view/SignUpType.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/button/ArabyteBoardCategoryButton.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/button/ArabyteCategoryButton.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/button/ArabyteFilteringButton.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/button/ArabyteLocationButton.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/textfield/ArabyteCareerTextField.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/textfield/ArabyteNormalTextField.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/signup/SignUpContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/signup/SignUpScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/signup/SignUpViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/signup/component/SignUpAgeGrid.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/signup/component/SignUpGenderRow.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/signup/component/SignUpLocationBottomSheet.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/signup/component/SignUpLocationList.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/signup/component/SignUpSuccessView.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/util/Constraints.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/util/base/BaseViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/util/base/UiEvent.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/util/base/UiSideEffect.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/util/base/UiState.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/util/view/LoadState.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/util/view/PageState.kt
  app/src/main/res/drawable/ic_all_location_check_14.xml
  app/src/main/res/drawable/img_signup_success.png
  app/src/main/res/values/strings.xml
Labels: feature, minseok

#24 Feat: 온보딩 UI 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/konkuk/arabyte_aos/presentation/model/ArabyteJobCategory.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/type/view/OnboardingType.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/type/view/SignUpType.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/button/ArabyteChipButton.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/onboarding/OnBoardingScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/onboarding/OnboardingContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/onboarding/component/OnboardingNumberChip.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/onboarding/component/OnboardingPageChip.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/onboarding/component/OnboardingSuccessView.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/util/Constraints.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/util/premission/PermissionUtils.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature, minseok

#22 Feat: 로그인 UI 구현 및 카카오 토큰 발급
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/konkuk/arabyte_aos/ArabyteApp.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/datalocal/datasource/UserInfoLocalDataSource.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/datalocal/datasourceimpl/UserInfoLocalDataSourceImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/repositoryimpl/UserInfoRepositoryImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/DataSourceModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/RepositoryModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/repository/UserInfoRepository.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/login/LoginContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/login/LoginScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/splash/SplashScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/util/log/DebugLog.kt
  app/src/main/res/drawable/ic_all_logo.xml
  app/src/main/res/drawable/ic_login_kakao_18.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: init, minseok

#28 Feat: 홈 화면 컴포넌트 구현
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/NoticeBoardItem.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/ArabyteNoticeBoardItem.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/chip/ArabyteIconTextChip.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/component/HomeContentTitle.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/component/HomeRegionChip.kt
  app/src/main/res/drawable/img_notice_board_image_load.xml
  app/src/main/res/values/strings.xml
Labels: feature, hwiwon

#29 Feat: 리뷰 리스트 화면 UI 구현
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/ReviewItem.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/type/component/ArabyteFilteringType.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/ArabyteReviewItem.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/bottomsheet/ArabyteCategoryBottomSheet.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/bottomsheet/ArabyteLocationBottomSheet.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/button/ArabyteAddFloationgButton.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/button/ArabyteFilteringButton.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/location/ArabyteLocationList.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/view/ArabyteEmptyView.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/review/ReviewScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewlist/ReviewListContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewlist/ReviewListScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewlist/ReviewListViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewlist/component/ReviewCategoryChip.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/signup/SignUpScreen.kt
  app/src/main/res/drawable/ic_all_refresh_22.xml
  app/src/main/res/drawable/ic_all_refresh_30.xml
  app/src/main/res/drawable/ic_review_list_pencil_24.xml
  app/src/main/res/values/strings.xml
Labels: feature, minseok

#31 Feat: 홈 화면 UI 구현
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/HomeContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/component/HomeCollapsedTopBar.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/component/HomeExpandedTopBar.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/component/HomePagerIndicator.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/component/HomeScreenContent.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/Navigator/MainNavHost.kt
  app/src/main/res/drawable/img_home_character.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature, hwiwon

#36 Feat: 게시글 상세 화면 UI 구현
  app/src/main/java/com/konkuk/arabyte_aos/presentation/model/NoticeBoardDetail.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/model/NoticeBoardDetailComment.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboarddetail/NoticeBoardDetailContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboarddetail/NoticeBoardDetailScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboarddetail/NoticeBoardDetailViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboarddetail/component/NoticeBoardDetailCommentBoard.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboarddetail/component/NoticeBoardDetailContent.kt
  app/src/main/res/drawable/img_profile_default_anonymity.png
  app/src/main/res/drawable/img_profile_default_female.png
  app/src/main/res/drawable/img_profile_default_male.png
Labels: feature, minseok

#35 Feat: 게시판 리스트 UI 구현
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/NoticeBoardItem.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/type/component/ArabyteNoticeBoardCategoryType.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/ArabyteNoticeBoardItem.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/button/ArabyteNoticeBoardCategoryButton.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/HomeContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/NoticeBoardListContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/NoticeBoardListScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/NoticeBoardListViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/component/NoticeBoardCategoryChip.kt
  app/src/main/res/drawable/ic_notice_board_list_note_24.xml
  app/src/main/res/values/strings.xml
Labels: feature, hwiwon

#38 Refactor: 중간 발표대비 화면 연결 및 버그 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasource/AuthRemoteDataSource.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasourceimpl/AuthRemoteDataSourceImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/interceptor/AuthInterceptor.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/interceptor/DummyInterceptor.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/response/AuthResponseDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/response/ReissueResponseDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/service/AuthService.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/mapper/todomain/AuthMapper.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/util/ApiConstraints.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/DataSourceModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/NetworkModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/RepositoryModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/ServiceModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/qualifier/Qualifier.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/Auth.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/repository/AuthRepository.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/type/MainNavigationBarItemType.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/ArabyteNoticeBoardItem.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/component/HomeScreenContent.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/login/LoginScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/login/navigation/LoginNavigation.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/MainScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/navigator/MainNavHost.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/navigator/MainNavigator.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/navigation/BottomNavigationExtension.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/navigation/RouteModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/NoticeBoardListScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/NoticeBoardScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/navigation/NoticeBoardNavigation.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboarddetail/navigation/NoticeBoardDetailNavigation.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/onboarding/OnBoardingScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/onboarding/OnboardingContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/review/ReviewScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewdetail/ReviewDetailScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewdetail/navigation/ReviewDetailNavigation.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewlist/ReviewListScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewlist/ReviewViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewlist/navigation/ReviewListNavigation.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/signup/SignUpContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/signup/SignUpScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/signup/navigation/SignUpNavigation.kt
  app/src/main/res/drawable/app_icon.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: refactor, minseok

#40 Feat: 유저관련 API 구현
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasource/AuthRemoteDataSource.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasource/UserRemoteDataSource.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasourceimpl/AuthRemoteDataSourceImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasourceimpl/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/interceptor/AuthInterceptor.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/request/PatchUserInfoRequestDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/request/PostOnboardingRequestDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/response/GetCheckNicknameResponseDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/response/PatchUserInfoResponseDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/service/AuthService.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/service/UserService.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/mapper/todata/UserOnboardingInfoMapper.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/mapper/todata/UserRegisterInfoMapper.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/mapper/todomain/NicknameCheckMapper.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/repositoryimpl/UserInfoRepositoryImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/util/ApiConstraints.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/DataSourceModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/ServiceModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/NicknameCheck.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/RegisterUserInfo.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/UserOnboardingInfo.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/repository/AuthRepository.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/repository/UserInfoRepository.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/user/DeleteUserUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/user/GetNicknameCheckUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/user/PatchUserInfoUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/user/PostOnboardingUserInfoUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/navigator/MainNavHost.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/navigator/MainNavigator.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/mypage/MyPageContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/mypage/navigation/MyPageNavigation.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/onboarding/OnBoardingScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/onboarding/OnboardingContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/signup/SignUpContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/signup/SignUpScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/signup/SignUpViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/util/context/ContextToastMessage.kt
  app/src/main/res/drawable/bg_all_toast_background.xml
  app/src/main/res/layout/arabyte_toast.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature, minseok
