Repository TEAM-Arabyte/Arabyte_AOS, pull requests merged in 2025-05, with the labels that each got.

#47 Feat: 리뷰 리스트, 상세 조회 API 연동
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasource/ReviewsRemoteDataSource.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasourceimpl/ReviewsRemoteDataSourceImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/response/GetReviewDetailResponseDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/response/GetReviewsResponseDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/service/ReviewService.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/mapper/todomain/ReviewDetailMapper.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/mapper/todomain/ReviewsMapper.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/repositoryimpl/ReviewsRepositoryImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/util/ApiConstraints.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/DataSourceModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/RepositoryModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/ServiceModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/ReviewDetail.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/ReviewItem.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/ReviewList.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/ReviewPageable.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/ReviewSort.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/repository/ReviewsRepository.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/reivew/GetReviewDetailUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/reivew/GetReviewListUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/model/ArabyteJobCategory.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/model/ReviewHelpful.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/ArabyteReviewItem.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/lazycolumn/InfinityLazyColumn.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/view/ArabyteEmptyView.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/HomeContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/navigator/MainNavigator.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/NoticeBoardListScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/component/NoticeBoardEmptyView.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboarddetail/NoticeBoardDetailScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboarddetail/component/NoticeBoardDetailCommentBoard.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboarddetail/component/NoticeBoardDetailCommentEmptyView.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewdetail/ReviewDetailContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewdetail/ReviewDetailScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewdetail/ReviewDetailViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewdetail/component/ReviewDetailContent.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewdetail/component/ReviewDetailHeader.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewdetail/navigation/ReviewDetailNavigation.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewlist/ReviewListContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewlist/ReviewListScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewlist/ReviewListViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewlist/component/ReviewListEmptyView.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewlist/navigation/ReviewListNavigation.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/signup/SignUpViewModel.kt
  app/src/main/res/drawable/ic_comment_empty_47.xml
  app/src/main/res/drawable/ic_notice_board_empty_100.xml
  app/src/main/res/drawable/ic_review_empty_100.xml
  app/src/main/res/values/strings.xml
Labels: feature, minseok

#54 Feat: 카카오 장소검색 Rest API 추가
  app/build.gradle.kts
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasource/KakaoRemoteDataSource.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasourceimpl/KakaoRemoteDataSourceImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/interceptor/KakaoInterceptor.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/response/KakaoSearchResponseDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/service/KakaoService.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/mapper/todomain/KakaoPlaceMapper.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/repositoryimpl/KakaoRepositoryImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/KakaoDataSourceProvidesModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/NetworkModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/RepositoryModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/ServiceModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/qualifier/Qualifier.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/KakaoPlace.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/repository/KakaoRepository.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/kakao/GetKakaoSearchUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewwrite/ReviewWriteContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewwrite/ReviewWriteScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewwrite/ReviewWriteViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewwrite/component/ReviewWritePlaceBottomSheet.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/reviewwrite/component/ReviewWritePlaceItem.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/util/modifier/ModifierExt.kt
  app/src/main/res/values/strings.xml
Labels: feature, minseok

#46 Feat: 중간 QA 구현
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/component/HomeCollapsedTopBar.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/component/HomeExpandedTopBar.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/navigation/BottomNavigationExtension.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/NoticeBoardListScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/NoticeBoardScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/util/BackHandler.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/util/PxtoDP.kt
  app/src/main/res/values/strings.xml
Labels: refactor, hwiwon

#52 Feat: 게시판/상세 API 및 댓글 UI
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasource/CommentDataSource.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasource/NoticeBoardRemoteDataSource.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasourceimpl/CommentDataSourceImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasourceimpl/NoticeBoardRemoteDataSourceImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/request/PostCommentRequestDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/response/GetNoticeBoardDetailResponseDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/response/GetNoticeBoardListResponseDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/response/PostCommentResponseDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/service/CommentService.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/service/NoticeBoardService.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/mapper/todata/PostCommentMapper.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/mapper/todomain/NoticeBoardDetailMapper.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/mapper/todomain/NoticeBoardsMapper.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/repositoryimpl/CommentRepositoryImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/repositoryimpl/NoticeBoardRepositoryImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/util/ApiConstraints.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/DataSourceModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/RepositoryModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/ServiceModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/NoticeBoardDetail.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/NoticeBoardItem.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/NoticeBoardList.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/PostComment.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/repository/CommentRepository.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/repository/NoticeBoardRepository.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/comment/PostCommentUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/noticeboard/GetNoticeBoardDetailUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/noticeboard/GetNoticeBoardListUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/model/NoticeBoardCommentNode.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/model/NoticeBoardDetail.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/model/NoticeBoardDetailComment.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/type/component/ArabyteNoticeBoardCategoryType.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/ArabyteNoticeBoardItem.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/chip/ArabyteIconTextChip.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/HomeContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/home/component/HomeScreenContent.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/navigator/MainNavHost.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/navigator/MainNavigator.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/NoticeBoardListContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/NoticeBoardListScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/NoticeBoardListViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/NoticeBoardScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/NoticeBoardViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/component/NoticeBoardCategoryChip.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/navigation/NoticeBoardNavigation.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboarddetail/NoticeBoardDetailContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboarddetail/NoticeBoardDetailScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboarddetail/NoticeBoardDetailViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboarddetail/component/NoticeBoardDetailCommentBoard.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboarddetail/component/NoticeBoardDetailCommentItem.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboarddetail/component/NoticeBoardDetailCommentTextField.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboarddetail/navigation/NoticeBoardDetailNavigation.kt
  app/src/main/res/values/strings.xml
Labels: feature, hwiwon

#57 Feat: 게시물 등록 UI 및 API 연동
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasource/NoticeBoardRemoteDataSource.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasourceimpl/NoticeBoardRemoteDataSourceImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/request/PostNoticeBoardWriteRequestDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/response/PostCommentResponseDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/service/NoticeBoardService.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/mapper/todata/PostNoticeBoardWriteMapper.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/repositoryimpl/NoticeBoardRepositoryImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/PostNoticeBoardWrite.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/repository/NoticeBoardRepository.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/noticeboard/PostNoticeBoardWriteUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/ArabyteTopAppBar.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/chip/ArabyteInformationBox.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/textfield/ArabyteNormalTextField.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/navigator/MainNavHost.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/main/navigator/MainNavigator.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/NoticeBoardListScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboard/navigation/NoticeBoardNavigation.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboardwrite/NoticeBoardWriteContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboardwrite/NoticeBoardWriteScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboardwrite/NoticeBoardWriteViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboardwrite/component/NoticeBoardWriteRequiredLabel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/noticeboardwrite/navigation/NoticeBoardWriteNavigation.kt
  app/src/main/res/drawable/ic_all_information_14.xml
  app/src/main/res/values/strings.xml
Labels: feature, hwiwon

#66 Feat: 마이페이지 구현
  app/build.gradle.kts
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasource/MyPageRemoteDataSource.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/datasourceimpl/MyPageRemoteDataSourceImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/response/ContractVerificationResponseDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/model/response/MyInfoResponseDto.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/dataremote/service/MyPageService.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/mapper/todomain/ContractVerificationMapper.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/mapper/todomain/MyInfoMapper.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/repositoryimpl/MyPageRepositoryImpl.kt
  app/src/main/java/com/konkuk/arabyte_aos/data/util/ApiConstraints.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/DataSourceModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/RepositoryModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/di/ServiceModule.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/ArabyteJobCategory.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/Contract.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/MyContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/model/MyInfo.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/repository/MyPageRepository.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/mypage/GetMyInfoUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/domain/usecase/mypage/PostContractVerificationUseCase.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/model/Gender.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/model/UserProfile.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/loading/ArabyteLoadingAnimation.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/component/view/ArabyteWebView.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/mypage/MyPageContract.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/mypage/component/MyPageAddContractButton.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/mypage/component/MyPageClickableText.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/mypage/component/MyPageContractView.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/mypage/component/MyPageMyContractItem.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/mypage/component/MyPageProfileDataText.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/mypage/component/MyPageProfileView.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/ui/mypage/component/MypageProfileRow.kt
  app/src/main/java/com/konkuk/arabyte_aos/presentation/util/Constraints.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature, minseok
